public_fqdn = ""
aws_region = "eu-west-2"
az_count = 2
ecs_fargate_version = "LATEST"
ecs_cluster_name = "exercise-programmer"
frontend_image = "exercise-frontend"
frontend_port = 3000
frontend_count = 
frontend_health_check_path = "/health"